/**
 * English translations for the Kinder Tracker app.
 */
export const en = {
  // Common
  common: {
    loading: 'Loading...',
    error: 'An error occurred',
    retry: 'Retry',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    close: 'Close',
    back: 'Back',
    next: 'Next',
    submit: 'Submit',
    search: 'Search',
    noResults: 'No results found',
  },

  // Authentication
  auth: {
    signIn: 'Sign In',
    signOut: 'Sign Out',
    createAccount: 'Create Account',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    firstName: 'First Name',
    lastName: 'Last Name',
    accountType: 'Account Type',
    schoolId: 'School ID',
    forgotPassword: 'Forgot Password?',
    noAccount: "Don't have an account?",
    hasAccount: 'Already have an account?',
    signInToManage: 'Sign in to manage your daycare',
    welcomeBack: 'Welcome back',
    enterCredentials: 'Enter your credentials to continue',
    createOne: 'Create one',
    emailRequired: 'Email is required',
    emailInvalid: 'Please enter a valid email address',
    passwordRequired: 'Password is required',
    passwordMinLength: 'Password must be at least 6 characters',
    passwordMismatch: 'Passwords do not match',
    firstNameRequired: 'First name is required',
    lastNameRequired: 'Last name is required',
    schoolIdRequired: 'School ID is required for your role',
    schoolIdNumber: 'School ID must be a number',
    invalidCredentials: 'Invalid email or password. Please try again.',
    checkFormat: 'Please check your email and password format.',
    serverError: 'Server error. Please try again.',
    cannotReachServer: 'Cannot reach the server. Check your connection.',
    registrationSuccess: 'Account created for {name}! Redirecting to sign in…',
    registrationFailed: 'Registration failed. Please check your details.',
    schoolNotFound: 'School not found. Please check the School ID.',
  },

  // Dashboard
  dashboard: {
    title: 'Dashboard',
    greeting: '👋 Hello,',
    welcomeMessage: 'More features are coming soon. You are successfully authenticated!',
    myChildren: 'My Children',
    myClasses: 'My Classes',
    myStudents: 'My Students',
    managementTools: 'Management Tools',
    manageTeachers: 'Manage Teachers',
    manageStudents: 'Manage Students',
    manageClasses: 'Manage Classes',
    manageParents: 'Manage Parents',
    manageTerms: 'Manage Terms',
    attendance: 'Attendance',
    events: 'Events',
    mealMenus: 'Meal Menus',
    reports: 'Reports',
    announcements: 'Announcements',
    quickActions: 'Quick Actions',
    managingSchool: 'Managing School',
    viewAll: 'View All',
    noChildren: 'No children linked to your account',
    noClasses: 'No classes assigned to you',
    noStudents: 'No students in your classes',
    childInfo: 'Child Information',
    classInfo: 'Class Information',
    studentInfo: 'Student Information',
  },

  // Roles
  roles: {
    admin: 'Admin',
    director: 'Director',
    teacher: 'Teacher',
    parent: 'Parent',
    student: 'Student',
  },

  // Student details
  student: {
    allergies: 'Allergies',
    noAllergies: 'No known allergies',
    dateOfBirth: 'Date of Birth',
    enrollmentDate: 'Enrollment Date',
    emergencyContact: 'Emergency Contact',
    medicalInfo: 'Medical Information',
  },

  // Class details
  class: {
    name: 'Class Name',
    capacity: 'Capacity',
    capacityUnlimited: 'Unlimited',
    enrolled: 'Enrolled',
    teacher: 'Teacher',
    schedule: 'Schedule',
    room: 'Room',
    createClass: 'Create Class',
    editClass: 'Edit Class',
    enrollStudents: 'Enroll Students',
    assignedStudents: 'Assigned Students',
    noAssignedStudents: 'No students assigned yet.',
    noStudentsAvailable: 'No students available for enrollment.',
    capacityRequired: 'Class capacity is required.',
    capacityInvalid: 'Class capacity must be a number.',
    capacityMin: 'Class capacity must be zero or greater.',
    capacityMax: 'Class capacity cannot exceed 30 students.',
    noClasses: 'No classes found',
    noClassesSubtitle: 'Classes will appear here once created',
    accessDenied: 'Class management is restricted',
    accessDeniedSubtitle: 'Please contact your administrator if you need access.',
    classDetails: 'Class Details',
    info: 'Class Information',
    currentStudents: 'Current Students',
    availableSpots: 'Available Spots',
    term: 'Term',
    students: 'Students',
    teachers: 'Teachers',
    assignedTeachers: 'Assigned Teachers',
    noAssignedTeachers: 'No teachers assigned yet.',
    availableStudents: 'Available Students',
    availableTeachers: 'Available Teachers',
    noTeachersAvailable: 'No teachers available for assignment.',
    notFound: 'Class Not Found',
    notFoundSubtitle: 'The requested class could not be found.',
    addStudents: 'Add Students',
    addTeachers: 'Add Teachers',
    remove: 'Remove',
    done: 'Done',
    searchStudents: 'Search students...',
    searchTeachers: 'Search teachers...',
    atCapacity: 'Class is at capacity. Remove a student to add new ones.',
    almostFull: 'Almost Full',
    spotsAvailable: 'spots available',
  },

  // Events
  events: {
    title: 'Events',
    noEvents: 'No Events Yet',
    noEventsSubtitle: 'Check back soon for upcoming events and activities!',
    upcoming: 'Upcoming Events',
    past: 'Past Events',
    createEvent: 'Create Event',
    editEvent: 'Edit Event',
    deleteEvent: 'Delete Event',
    eventTitle: 'Event Title',
    eventDate: 'Event Date',
    eventTime: 'Event Time',
    eventDescription: 'Description',
    eventPhoto: 'Photo (optional)',
    confirmDelete: 'Are you sure you want to delete this event?',
    selectSchool: 'Select School',
    selectClass: 'Select Class',
    noClassesAvailable: 'No classes available for this school.',
    classRequired: 'Please select a class for the event.',
    titleRequired: 'Event title is required.',
  },

  // Terms
  terms: {
    title: 'Terms',
    create: 'Create Term',
    edit: 'Edit Term',
    name: 'Term Name',
    nameRequired: 'Term name is required.',
    schoolRequired: 'Please select a school to manage terms.',
    imageUrl: 'Term Image URL',
    imageUrlPlaceholder: 'https://example.com/term.png',
    startDate: 'Start Date',
    endDate: 'End Date',
    noEndDate: 'No end date',
    active: 'Active',
    inactive: 'Inactive',
    status: 'Status',
    selectSchool: 'Select School',
    activeTerm: 'Active term',
    noActiveTerm: 'No active term found for this school.',
    assignedClasses: 'Assigned classes',
    noAssignedClasses: 'No classes assigned yet.',
    manageClasses: 'Manage classes',
    noClassesAvailable: 'No classes available for this school.',
    noTerms: 'No terms found',
    noTermsSubtitle: 'Create a term to start organizing classes.',
    imageAttached: 'Image attached',
    saveFailed: 'Unable to save term. Please try again.',
    deleteFailed: 'Unable to delete term. Please try again.',
    assignFailed: 'Unable to update class assignments.',
    invalidDateRange: 'Start date cannot be after end date.',
    invalidImageUrl: 'Term image URL must start with http.',
    classCount: '{count} class(es) assigned',
    selectSchoolHint: 'Select a school to view terms for that location.',
    // Term detail screen
    termDetails: 'Term Details',
    totalCapacity: 'Total Capacity',
    termInactive: 'This term is not active. Class assignments are read-only.',
    viewDetails: 'View Details',
    manageAssignments: 'Manage Assignments',
    classAssignments: 'Class Assignments',
    assignClass: 'Assign Class',
    unassignClass: 'Unassign Class',
    noClassesToAssign: 'No classes available to assign.',
    searchClasses: 'Search classes...',
    assignmentUpdated: 'Assignment updated successfully.',
  },

  mealMenus: {
    schoolRequired: 'Please select a school to create a meal menu.',
    itemsRequired: 'Add at least one meal item before saving.',
  },

  // Navigation
  nav: {
    home: 'Home',
    profile: 'Profile',
    settings: 'Settings',
    notifications: 'Notifications',
  },
} as const;

export type Translations = typeof en;
